[package]
name = "pallet-poc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/spartan-node-template"
description = "Consensus extension module for PoC consensus. Collects on-chain randomness from VRF outputs and manages epoch transitions."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "3.1.0", default-features = false, path = "../benchmarking", optional = true }
frame-support = { version = "3.0.0", default-features = false, path = "../support" }
frame-system = { version = "3.0.0", default-features = false, path = "../system" }
pallet-authorship = { version = "3.0.0", default-features = false, path = "../authorship" }
pallet-timestamp = { version = "3.0.0", default-features = false, path = "../timestamp" }
serde = { version = "1.0.101", optional = true }
sp-consensus-poc = { version = "0.1.0", default-features = false, path = "../../primitives/consensus/poc" }
sp-consensus-vrf = { version = "0.9.0", default-features = false, path = "../../primitives/consensus/vrf" }
sp-io = { version = "3.0.0", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../primitives/runtime" }
sp-staking = { version = "3.0.0", default-features = false, path = "../../primitives/staking" }
sp-std = { version = "3.0.0", default-features = false, path = "../../primitives/std" }
log = { version = "0.4.14", default-features = false }

[dev-dependencies]
pallet-balances = { version = "3.0.0", path = "../balances" }
pallet-offences = { version = "3.0.0", path = "../offences" }
pallet-staking = { version = "3.0.0", path = "../staking" }
pallet-staking-reward-curve = { version = "3.0.0", path = "../staking/reward-curve" }
sp-core = { version = "3.0.0", path = "../../primitives/core" }
frame-election-provider-support = { version = "3.0.0", path = "../election-provider-support" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-timestamp/std",
	"serde",
	"sp-consensus-poc/std",
	"sp-consensus-vrf/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-std/std",
	"log/std",
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
