version: "3"
services:
  node:
    image: subspacelabs/node-template-spartan
    networks:
      - default
      - spartan
    command: [
        "--dev",
        "--tmp",
        "--ws-external",
        "--bootnodes", "/ip4/${BOOTSTRAP_CLIENT_IP}/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
    ]
  farmer:
    image: subspacelabs/spartan-farmer
    networks:
      - default
    volumes:
      - source: spartan-farmer
        target: /var/spartan
        type: volume
    restart: always
    command: [
        "farm",
        "--ws-server", "ws://node:9944"
    ]

networks:
  spartan:
    external: true
    name: spartan

volumes:
  spartan-farmer:
    external: true
    name: spartan-farmer-${INSTANCE_ID}
