[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = '2018'
name = 'pallet-template-spartan'
version = "0.1.0"
license = "Unlicense"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/substrate"
description = "FRAME pallet template for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { default-features = false, version = "4.0.0-dev", path = "../../../../frame/support" }
frame-system = { default-features = false,  version = "4.0.0-dev",  path = "../../../../frame/system" }
frame-benchmarking = { default-features = false,  version = "4.0.0-dev",  path = "../../../../frame/benchmarking", optional = true }

[dev-dependencies]
serde = { version = "1.0.127" }
sp-core = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/core" }
sp-io = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/io" }
sp-runtime = { default-features = false, version = "4.0.0-dev", path = "../../../../primitives/runtime" }

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
