[package]
name = "sp-consensus-poc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Subspace Labs <admin@subspace.network>"]
description = "Primitives for PoC consensus"
edition = "2018"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/substrate"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-application-crypto = { version = "4.0.0-dev", default-features = false, path = "../../application-crypto" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-std = { version = "4.0.0-dev", default-features = false, path = "../../std" }
sp-api = { version = "4.0.0-dev", default-features = false, path = "../../api" }
sp-consensus = { version = "0.10.0-dev", optional = true, path = "../common" }
sp-consensus-slots = { version = "0.10.0-dev", default-features = false, path = "../slots" }
sp-consensus-spartan = { version = "0.1.0", path = "../spartan", default-features = false }
sp-core = { version = "4.0.0-dev", default-features = false, path = "../../core" }
sp-inherents = { version = "4.0.0-dev", default-features = false, path = "../../inherents" }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../../runtime" }
sp-timestamp = { version = "4.0.0-dev", path = "../../timestamp", optional = true }
serde = { version = "1.0.127", features = ["derive"], optional = true }
async-trait = { version = "0.1.51", optional = true }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"sp-std/std",
	"sp-api/std",
	"sp-consensus",
	"sp-consensus-slots/std",
	"sp-consensus-spartan/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"serde",
	"sp-timestamp",
	"async-trait",
]
