[package]
name = "sp-consensus-poc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for PoC consensus"
edition = "2018"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/spartan-node-template"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-application-crypto = { version = "3.0.0", default-features = false, path = "../../application-crypto" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
merlin = { version = "2.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false, path = "../../std" }
sp-api = { version = "3.0.0", default-features = false, path = "../../api" }
sp-consensus = { version = "0.9.0", optional = true, path = "../common" }
sp-consensus-slots = { version = "0.9.0", default-features = false, path = "../slots" }
sp-consensus-spartan = { version = "0.1.0", path = "../spartan", default-features = false }
sp-core = { version = "3.0.0", default-features = false, path = "../../core" }
sp-inherents = { version = "3.0.0", default-features = false, path = "../../inherents" }
sp-keystore = { version = "0.9.0", default-features = false, path = "../../keystore", optional = true }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../runtime" }
sp-timestamp = { version = "3.0.0", default-features = false, path = "../../timestamp" }
serde = { version = "1.0.123", features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"merlin/std",
	"sp-std/std",
	"sp-api/std",
	"sp-consensus",
	"sp-consensus-slots/std",
	"sp-consensus-spartan/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-keystore",
	"sp-runtime/std",
	"sp-timestamp/std",
	"serde",
]
