[package]
name = "sc-consensus-poc-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Subspace Labs <admin@subspace.network>"]
description = "RPC extensions for the PoC consensus algorithm"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/substrate"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-consensus-poc = { version = "0.1.0", path = ".." }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../rpc-api" }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
jsonrpc-pubsub = "15.1.0"
sp-consensus-poc = { version = "0.1.0", path = "../../../../primitives/consensus/poc" }
serde = { version = "1.0.127", features = ["derive"] }
futures = { version = "0.3.16", features = ["compat"] }
futures-timer = "3.0.2"
sp-core = { version = "4.0.0-dev", path = "../../../../primitives/core" }
log = "0.4.14"
parking_lot = "0.11.1"

[dev-dependencies]
